First of all, we'll do the same thing as `list` did for `array`.

In [2]:
import numpy as np
arr = np.arange(0, 10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
arr[8]

8

In [5]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [6]:
arr[4:]

array([4, 5, 6, 7, 8, 9])

In [4]:
arr[1:5]

array([1, 2, 3, 4])

### **Broadcasting.**

Numpy arrays differ from a normal Python list because of their ability to broadcast:

In [8]:
arr[0:5] = 100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9])

In [9]:
slice_of_arr = np.arange(0, 6)
slice_of_arr[:] = 99
slice_of_arr

array([99, 99, 99, 99, 99, 99])

But pay attention to the problem of assigning an array to a variable, specifically as follows:

In [10]:
arr = np.arange(0, 10)
slice_of_arr = arr[0:6]
slice_of_arr[:] = 99
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [11]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9])

As you can see, when you change `slice_of_arr`, `arr` will also be changed.

To avoid this situation, you should do the following:

In [12]:
arr_copy = arr.copy()
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9])

In [13]:
arr_copy[:] = 100
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [14]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9])

### **Indexing a 2D array (matrices).**

The general format is `arr_2d[row][col]` or `arr_2d[row,col]`. I recommend usually using the comma notation for clarity.

In [16]:
arr_2d = np.array([[5, 10, 15], [20, 25, 30], [35, 40, 45]])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [17]:
arr_2d[1]

array([20, 25, 30])

In [18]:
arr_2d[1][0]

20

In [19]:
arr_2d[1, 1]

25

With a similar way of thinking as a 1-dimensional array, we will do the following:

In [20]:
arr_2d[:2, 1:] # This means I want to get all the elements from row 0 to row 1, from column 1 to the end

array([[10, 15],
       [25, 30]])

In [23]:
arr_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [26]:
arr_2d[2, 1:]

array([40, 45])

### **Selection.**

In [28]:
arr = np.arange(1, 11)
bool_arr = arr > 5
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [29]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [30]:
arr[arr > 5]

array([ 6,  7,  8,  9, 10])

In [31]:
arr[arr < 3]

array([1, 2])

### **Fancy indexing.**

In [38]:
from numpy.random import randint
arr2d = randint(1, 100, (8, 10))
arr2d

array([[95, 64, 94, 84, 67, 35, 62,  3, 26, 21],
       [13, 17, 90,  1, 61, 76, 81, 79, 58, 75],
       [50, 17, 13, 72, 39, 93, 99, 84, 97, 95],
       [18, 70,  6,  6, 22, 34, 87, 96, 70, 53],
       [73, 62, 11, 34, 62, 73, 81, 32, 75, 27],
       [40, 85,  4, 84, 93, 82, 76, 68, 92, 80],
       [26,  3, 82, 84, 10, 98, 70, 60, 41, 99],
       [39, 21, 66, 97, 76, 59, 10, 84, 93, 50]])

In [44]:
# Size of two-dimensional array
row, column = arr2d.shape
print(row, column)

8 10


When you use the syntax `arr2d[[2, 4, 6, 7]]`, you are asking to access the rows with indices 2, 4, 6, and 8 in the two-dimensional array `arr2d`. The result will be a new array containing these rows.

In [43]:
arr2d[[2, 4, 6, 7]]

array([[50, 17, 13, 72, 39, 93, 99, 84, 97, 95],
       [73, 62, 11, 34, 62, 73, 81, 32, 75, 27],
       [26,  3, 82, 84, 10, 98, 70, 60, 41, 99],
       [39, 21, 66, 97, 76, 59, 10, 84, 93, 50]])

In [45]:
arr2d[[6, 3, 1, 5]]

array([[26,  3, 82, 84, 10, 98, 70, 60, 41, 99],
       [18, 70,  6,  6, 22, 34, 87, 96, 70, 53],
       [13, 17, 90,  1, 61, 76, 81, 79, 58, 75],
       [40, 85,  4, 84, 93, 82, 76, 68, 92, 80]])